const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const K='focuslist_clean_v2',AK='focuslist_auth_v2';
let filter='all',category='Work',reminder=true,user=null;
const now=new Date();const iso=d=>{const p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};
const addTime=(days,h,m)=>{let d=new Date();d.setDate(d.getDate()+days);d.setHours(h,m,0,0);return iso(d)};
const seed=[['Study DSA',0,9,0,'Study','💻',false],['Workout',0,18,0,'Health','💪',false],['Read a book',0,8,0,'Personal','📖',true],['Complete project',1,10,0,'Work','💼',false],['Plan weekend trip',4,13,0,'Personal','✈️',false]].map((x,i)=>({id:i+1,title:x[0],date:addTime(x[1],x[2],x[3]),category:x[4],emoji:x[5],done:x[6],description:'',reminder:true}));
function allData(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return{}}}function tasks(){return allData()[user.email]||structuredClone(seed)}function setTasks(v){const d=allData();d[user.email]=v;localStorage.setItem(K,JSON.stringify(d))}
function same(a,b){return a.toDateString()===b.toDateString()}function label(t){let d=new Date(t.date),n=new Date();let day=same(d,n)?'Today':same(d,new Date(n.getFullYear(),n.getMonth(),n.getDate()+1))?'Tomorrow':d.toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'});return `${day} · ${d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){let ts=tasks();let f=ts.filter(t=>filter==='all'||filter==='completed'&&t.done||filter==='today'&&same(new Date(t.date),new Date())&&!t.done||filter==='upcoming'&&new Date(t.date)>new Date()&&!same(new Date(t.date),new Date())&&!t.done);$('#taskList').innerHTML=f.length?f.map(t=>`<article class="task ${t.done?'done':''}"><button class="check ${t.done?'done':''}" data-id="${t.id}">${t.done?'✓':''}</button><div class="task-main"><div class="task-title">${esc(t.title)}</div><div class="meta">${t.emoji||'📝'} &nbsp;${label(t)}</div></div><span class="tag ${t.category}">${t.category}</span></article>`).join(''):'<div style="text-align:center;color:#8492a5;padding:40px 0">No tasks here yet.</div>';$$('.check').forEach(b=>b.onclick=()=>{let v=tasks();v=v.map(t=>t.id===+b.dataset.id?{...t,done:!t.done}:t);setTasks(v);render()});renderPreview()}
function renderPreview(){let t=tasks().filter(x=>same(new Date(x.date),new Date()));$('#todayCount').textContent=`${t.length} task${t.length===1?'':'s'}`;$('#preview').innerHTML=t.map(x=>`<div class="preview-item"><span>${x.done?'☑':'☐'} ${esc(x.title)}</span><small>${new Date(x.date).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div>`).join('')||'<div style="color:#7f8ca0">No tasks for today.</div>'}
function openAdd(){$('#addScreen').classList.remove('hidden');$('#titleInput').focus();let d=new Date();d.setMinutes(Math.ceil(d.getMinutes()/15)*15);$('#dateInput').value=iso(d)}function closeAdd(){$('#addScreen').classList.add('hidden')}
function save(){let title=$('#titleInput').value.trim();if(!title){$('#titleInput').focus();return}let ts=tasks();ts.unshift({id:Date.now(),title,date:$('#dateInput').value||iso(new Date()),category,emoji:{Work:'💼',Study:'💻',Personal:'📖',Health:'💪'}[category],done:false,description:$('#descInput').value.trim(),reminder});setTasks(ts);$('#titleInput').value='';$('#descInput').value='';closeAdd();render()}
function auth(){let a=JSON.parse(localStorage.getItem(AK)||'null');if(a?.email){user=a;$('#login').classList.remove('show');render()}else $('#login').classList.add('show')}
$('#authBtn').onclick=()=>{let e=$('#email').value.trim(),p=$('#password').value;if(!e||!p){$('#authError').textContent='Enter email and password.';return}let accounts=JSON.parse(localStorage.getItem('focuslist_accounts')||'{}');let register=$('#authBtn').dataset.mode==='register';if(register){if(accounts[e]){$('#authError').textContent='Account already exists. Log in instead.';return}accounts[e]=p;localStorage.setItem('focuslist_accounts',JSON.stringify(accounts))}else if(accounts[e]!==p){$('#authError').textContent='Invalid email or password.';return}localStorage.setItem(AK,JSON.stringify({email:e}));auth()};
$('#switchAuth').onclick=()=>{let b=$('#authBtn'),r=b.dataset.mode==='register';b.dataset.mode=r?'login':'register';b.textContent=r?'Log in':'Create account';$('#switchAuth').textContent=r?'Create a new account':'Already have an account? Log in';$('#authError').textContent=''};
$('#menuBtn').onclick=()=>$('#menuPanel').classList.toggle('show');$('#logout').onclick=()=>{localStorage.removeItem(AK);location.reload()};$('#clear').onclick=()=>{if(confirm('Clear all tasks?')){setTasks([]);render();$('#menuPanel').classList.remove('show')}};$('#restore').onclick=()=>{setTasks(structuredClone(seed));render();$('#menuPanel').classList.remove('show')};
$('#addBtn').onclick=openAdd;$('#backBtn').onclick=closeAdd;$('#saveBtn').onclick=save;$('#chips').onclick=e=>{if(!e.target.matches('.chip'))return;category=e.target.dataset.cat;$$('.chip').forEach(x=>x.classList.toggle('selected',x.dataset.cat===category))};$('#reminder').onclick=()=>{reminder=!reminder;$('#reminder').classList.toggle('off',!reminder)};$('#tabs').onclick=e=>{if(e.target.tagName!=='BUTTON')return;filter=e.target.dataset.filter;$$('#tabs button').forEach(b=>b.classList.toggle('active',b===e.target));render()};
$('#fullBtn').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{alert('Fullscreen is controlled by your browser.') }};
$('#calendar').onclick=()=>alert('Calendar view is coming next.');$('#stats').onclick=()=>{let t=tasks(),done=t.filter(x=>x.done).length;alert(`Tasks: ${t.length}\nCompleted: ${done}`)};$('#settings').onclick=()=>$('#menuPanel').classList.toggle('show');auth();
