-- Optional Supabase backend starter for FocusList
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  description text default '',
  due_at timestamptz not null default now(),
  category text not null default 'Work' check (category in ('Work','Study','Personal','Health')),
  emoji text default '📝',
  completed boolean not null default false,
  reminder boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;

create policy "Users can view their tasks"
on public.tasks for select
using (auth.uid() = user_id);

create policy "Users can insert their tasks"
on public.tasks for insert
with check (auth.uid() = user_id);

create policy "Users can update their tasks"
on public.tasks for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their tasks"
on public.tasks for delete
using (auth.uid() = user_id);
